# -*- coding: utf-8 -*-
"""mylms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0Q2MEJHmPNF06d-RN7GJiiJEDHg7h3w
"""

class Library:
    def __init__(self):
        self.books = []

    def list_books(self):
        if self.books:
            print("List of Books:")
            for book in self.books:
                print(f"Title: {book['title']}, Author: {book['author']}")
        else:
            print("No books in the library.")

    def add_book(self, title, author, publication_date, pages):
        book = {'title': title, 'author': author, 'publication_date': publication_date, 'pages': pages}
        self.books.append(book)
        with open("book.txt", "a+") as file:
            file.write(f"{book}\n")
        print(f"Book '{title}' by {author} added successfully.")

    def remove_book(self, title):
        removed = False
        for book in self.books:
            if book['title'] == title:
                self.books.remove(book)
                removed = True
                print(f"Book '{title}' removed successfully.")
                break
        if not removed:
            print(f"Book '{title}' not found in the library.")
        with open("book.txt", "w") as file:
            for book in self.books:
                file.write(f"{book}\n")


def main():
    lib = Library()

    while True:
        print("***MENU***")
        print("1. List Books")
        print("2. Add Book")
        print("3. Remove Book")
        print("4. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            lib.list_books()
        elif choice == '2':
            title = input("Enter the title of the book: ")
            author = input("Enter the author of the book: ")
            publication_date = input("Enter the publication date of the book: ")
            pages = input("Enter the number of pages: ")
            lib.add_book(title, author, publication_date, pages)
        elif choice == '3':
            title = input("Enter the title of the book to remove: ")
            lib.remove_book(title)
        elif choice == '4':
            print("Exiting the program.")
            break


if __name__ == "__main__":
    main()